package test.Customer.MaintainCustomer.Ref;

import com.company.functions;

import java.util.ArrayList;

public class LISTCONTENT_MaintainCustomer {
    private functions use = new functions();
    private static ArrayList<String> countryCodes = new ArrayList<>();

    public static ArrayList<String> getArrayList() {
        countryCodes.add("Afghanistan");
        countryCodes.add("Albania");
        countryCodes.add("Algeria");
        countryCodes.add("American Samoa");
        countryCodes.add("Andorra");
        countryCodes.add("Angola");
        countryCodes.add("Anguilla");
        countryCodes.add("Antigua and Barbuda");
        countryCodes.add("Argentina");
        countryCodes.add("Armenia");
        countryCodes.add("Aruba");
        countryCodes.add("Australia");
        countryCodes.add("Austria");
        countryCodes.add("Azerbaijan");
        countryCodes.add("Bahamas");
        countryCodes.add("Bahrain");
        countryCodes.add("Bangladesh");
        countryCodes.add("Barbados");
        countryCodes.add("Belarus");
        countryCodes.add("Belgium");
        countryCodes.add("Belize");
        countryCodes.add("Benin");
        countryCodes.add("Bermuda");
        countryCodes.add("Bhutan");
        countryCodes.add("Bolivia");
        countryCodes.add("Bosnia and Herzegovina");
        countryCodes.add("Botswana");
        countryCodes.add("Brazil");
        countryCodes.add("British Indian Ocean Territory");
        countryCodes.add("VIRGIN ISLANDS (BRITISH)");
        countryCodes.add("Brunei");
        countryCodes.add("Bulgaria");
        countryCodes.add("Burkina Faso");
        countryCodes.add("Burundi");
        countryCodes.add("Cambodia");
        countryCodes.add("Cameroon");
        countryCodes.add("Canada");
        countryCodes.add("Cape Verde");
        countryCodes.add("Cayman Islands");
        countryCodes.add("Central African Republic");
        countryCodes.add("Chad");
        countryCodes.add("Chile");
        countryCodes.add("China");
        countryCodes.add("Christmas Island");
        countryCodes.add("Colombia");
        countryCodes.add("Comoros");
        countryCodes.add("Cook Islands");
        countryCodes.add("Costa Rica");
        countryCodes.add("Croatia");
        countryCodes.add("Cuba");
        countryCodes.add("Curaçao");
        countryCodes.add("Cyprus");
        countryCodes.add("Czech Republic");
        countryCodes.add("CONGO, THE DEMOCRATIC REPUBLIC OF");
        countryCodes.add("Denmark");
        countryCodes.add("Djibouti");
        countryCodes.add("Dominica");
        countryCodes.add("Dominican Republic");
        countryCodes.add("Ecuador");
        countryCodes.add("Egypt");
        countryCodes.add("El Salvador");
        countryCodes.add("Equatorial Guinea");
        countryCodes.add("Eritrea");
        countryCodes.add("Estonia");
        countryCodes.add("Ethiopia");
        countryCodes.add("Falkland Islands");
        countryCodes.add("Faroe Islands");
        countryCodes.add("Fiji");
        countryCodes.add("Finland");
        countryCodes.add("France");
        countryCodes.add("French Polynesia");
        countryCodes.add("Gabon");
        countryCodes.add("Gambia");
        countryCodes.add("Georgia");
        countryCodes.add("Germany");
        countryCodes.add("Ghana");
        countryCodes.add("Gibraltar");
        countryCodes.add("Greece");
        countryCodes.add("Greenland");
        countryCodes.add("Grenada");
        countryCodes.add("Guam");
        countryCodes.add("Guatemala");
        countryCodes.add("Guernsey");
        countryCodes.add("Guinea");
        countryCodes.add("Guinea-Bissau");
        countryCodes.add("Guyana");
        countryCodes.add("Haiti	");
        countryCodes.add("Honduras");
        countryCodes.add("Hong Kong");
        countryCodes.add("Hungary");
        countryCodes.add("Iceland");
        countryCodes.add("India");
        countryCodes.add("Indonesia");
        countryCodes.add("Iran");
        countryCodes.add("Iraq");
        countryCodes.add("Ireland");
        countryCodes.add("Isle of Man");
        countryCodes.add("Israel");
        countryCodes.add("Italy");
        countryCodes.add("Jamaica");
        countryCodes.add("Japan");
        countryCodes.add("Jersey");
        countryCodes.add("Jordan");
        countryCodes.add("Kazakhstan");
        countryCodes.add("Kenya");
        countryCodes.add("Kiribati");
        countryCodes.add("Kosovo");
        countryCodes.add("Kuwait");
        countryCodes.add("Kyrgyzstan");
        countryCodes.add("Laos");
        countryCodes.add("Latvia");
        countryCodes.add("Lebanon");
        countryCodes.add("Lesotho");
        countryCodes.add("Liberia");
        countryCodes.add("Libya");
        countryCodes.add("Liechtenstein");
        countryCodes.add("Lithuania");
        countryCodes.add("Luxembourg");
        countryCodes.add("Macedonia");
        countryCodes.add("Madagascar");
        countryCodes.add("Malawi");
        countryCodes.add("Malaysia");
        countryCodes.add("Maldives");
        countryCodes.add("Mali");
        countryCodes.add("Malta");
        countryCodes.add("Marshall Islands");
        countryCodes.add("Mauritania");
        countryCodes.add("Mauritius");
        countryCodes.add("Mayotte");
        countryCodes.add("Mexico");
        countryCodes.add("Micronesia");
        countryCodes.add("Moldova");
        countryCodes.add("Monaco");
        countryCodes.add("Mongolia");
        countryCodes.add("Montenegro");
        countryCodes.add("Montserrat");
        countryCodes.add("Morocco");
        countryCodes.add("Mozambique");
        countryCodes.add("Myanmar");
        countryCodes.add("Namibia");
        countryCodes.add("Nauru");
        countryCodes.add("Nepal");
        countryCodes.add("Netherlands");
        countryCodes.add("New Caledonia");
        countryCodes.add("New Zealand");
        countryCodes.add("Nicaragua");
        countryCodes.add("Niger");
        countryCodes.add("Nigeria");
        countryCodes.add("Niue");
        countryCodes.add("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF");
        countryCodes.add("Northern Mariana Islands");
        countryCodes.add("Norway");
        countryCodes.add("Oman");
        countryCodes.add("Pakistan");
        countryCodes.add("Palau");
        countryCodes.add("Palestine");
        countryCodes.add("Panama");
        countryCodes.add("Papua New Guinea");
        countryCodes.add("Paraguay");
        countryCodes.add("Peru");
        countryCodes.add("Philippines");
        countryCodes.add("Poland");
        countryCodes.add("Portugal");
        countryCodes.add("Puerto Rico");
        countryCodes.add("Qatar");
        countryCodes.add("Congo");

        countryCodes.add("Romania");
        countryCodes.add("Russia");
        countryCodes.add("Rwanda");
        countryCodes.add("Saint Helena");
        countryCodes.add("Saint Kitts and Nevis");
        countryCodes.add("Saint Lucia");
        countryCodes.add("Saint Martin");
        countryCodes.add("Saint Pierre and Miquelon");
        countryCodes.add("Saint Vincent and the Grenadines");
        countryCodes.add("Samoa");
        countryCodes.add("San Marino");
        countryCodes.add("Sao Tome and Principe");
        countryCodes.add("Saudi Arabia");
        countryCodes.add("Senegal");
        countryCodes.add("Serbia");
        countryCodes.add("Seychelles");
        countryCodes.add("Sierra Leone");
        countryCodes.add("Singapore");
        countryCodes.add("Slovakia");
        countryCodes.add("Slovenia");
        countryCodes.add("Solomon Islands");
        countryCodes.add("Somalia");
        countryCodes.add("South Africa");
        countryCodes.add("South Sudan");
        countryCodes.add("Spain");
        countryCodes.add("Sri Lanka");
        countryCodes.add("Sudan");
        countryCodes.add("Suriname");
        countryCodes.add("Svalbard and Jan Mayen");
        countryCodes.add("Swaziland");
        countryCodes.add("Sweden");
        countryCodes.add("Switzerland");
        countryCodes.add("Syria");
        countryCodes.add("Taiwan");
        countryCodes.add("Tajikistan");
        countryCodes.add("Tanzania");
        countryCodes.add("Thailand");
        countryCodes.add("Togo");
        countryCodes.add("Tokelau");
        countryCodes.add("Tonga");
        countryCodes.add("Trinidad and Tobago");
        countryCodes.add("Tunisia");
        countryCodes.add("Turkey");
        countryCodes.add("Turkmenistan");
        countryCodes.add("Turks and Caicos Islands");
        countryCodes.add("Tuvalu");
       countryCodes.add("VIRGIN ISLANDS (U.S.)");
        countryCodes.add("Uganda");
        countryCodes.add("Ukraine");
        countryCodes.add("United Arab Emirates");
        countryCodes.add("United Kingdom");
        countryCodes.add("United States");
        countryCodes.add("Uruguay");
        countryCodes.add("Uzbekistan");
        countryCodes.add("Vanuatu");
        //countryCodes.add("Vatican");
        countryCodes.add("Venezuela");
        countryCodes.add("Vietnam");
        countryCodes.add("Wallis and Futuna");
        countryCodes.add("Western Sahara");
        countryCodes.add("Yemen");
        countryCodes.add("Zambia");
        countryCodes.add("Zimbabwe");
        countryCodes.add("KOREA, REPUBLIC OF");
        return countryCodes;
    }
}
